app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import db, lm

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(16), index=True, unique=True)
    age = db.Column(db.Integer)
    email = db.Column(db.String(16))
    password_hash = db.Column(db.String(64))

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    @staticmethod
    def register(name, age, email, password):
        user = User(name=name, age=age, email=email)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        return user

    def __repr__(self):
        return '<User {0}>'.format(self.name)

@lm.user_loader
def load_user(id):
    return User.query.get(int(id))

app/main/forms.py
from flask_wtf import Form
from wtforms import StringField, SelectField, SubmitField, PasswordField, BooleanField
from wtforms.validators import Required, Length, Email, EqualTo
from wtforms.fields.html5 import EmailField

class LoginForm(Form):
    name = StringField('Introduce yourself', validators=[Required(), Length(1, 16)])
    password = PasswordField('Your Password', validators=[Required(), Length(1, 16)])
    remember_me = BooleanField('Remember me')
    submit = SubmitField('Submit')


class RegistrationForm(Form):
    name = StringField('What is your name?', validators=[Required(), Length(1, 16)])
    age = SelectField('Your age', choices=[(str(i), str(i)) for i in range(10, 100)])
    email = EmailField('Email address', validators=[Required(), Email()])
    password = PasswordField('Your Password', validators=[Required(), Length(1, 16),
                                                          EqualTo('pass_repeat', message='Passwords must match.')])
    pass_repeat = PasswordField('Repeat Password', validators=[Required(), Length(1, 16)])
    submit = SubmitField('Register')

app/__init__.py
import os
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

bootstrap = Bootstrap()
db = SQLAlchemy()
lm = LoginManager()
lm.login_view = 'main.login'


def create_app(config_name):
    app = Flask(__name__)

    cfg = os.path.join(os.getcwd(), 'config', config_name + '.py')
    app.config.from_pyfile(cfg)

    bootstrap.init_app(app)
    db.init_app(app)
    lm.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes

app/main/routes.py
from flask import render_template, redirect, url_for
from flask_login import login_required, login_user, logout_user
from ..models import User
from . import main
from .forms import LoginForm, RegistrationForm


@main.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        password = form.password.data
        user = User.query.filter_by(name=form.name.data).first()
        if user is not None and user.verify_password(password):
            login_user(user, form.remember_me.data)
            return redirect(url_for('main.welcome'))
        elif user is None:
            new = True
            return render_template('login.html', form=form, new=new)
        else:
            wrong_pass = True
            return render_template('login.html', form=form, name=user.name, wrong_pass=wrong_pass)
    return render_template('login.html', form=form)


@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.welcome'))


@main.route("/")
def welcome():
    return render_template("welcome.html")


@main.route("/registration", methods=['GET', 'POST'])
def registration():
    form = RegistrationForm()
    if form.validate_on_submit():
        name = form.name.data
        age = form.age.data
        email = form.email.data
        password = form.password.data
        form.name.data = ''
        form.age.data = ''
        form.email.data = ''
        form.password.data = ''
        if User.query.filter_by(name=name).first() is None:
            User.register(name, age, email, password)
        else:
            already_exists = True
            return render_template("registration.html", form=form, already_exists=already_exists, name=name)
        return redirect(url_for('main.login'))
    return render_template("registration.html", form=form)


@main.route("/disk")
def disk():
    return render_template("disk.html")

app/templates/disk.html
{% extends 'layout.html' %}
{% set active_page = "/disk" %}

{% block content %}
    <div class="container">
        <h1>Disk</h1>
    </div>
{% endblock %}

app/templates/layout.html
{% extends 'bootstrap/base.html' %}

{% block title %}Blog{% endblock %}

{% block navbar %}
    {% if not current_user.is_authenticated %}
        {% set button_logname = '/login', '/login', 'Login' %}
    {% else %}
        {% set button_logname = '/logout', '/logout', 'Logout' %}
    {% endif %}
    {% set navigation_bar = [('/', '/', 'Welcome'), ('/disk', '/disk', 'Disk'),
                               button_logname ]%}
    {% set active_page = active_page|default('/') %}
    <div class="navbar navbar-inverse">
        <div class="container">

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand text-muted" href="/">Blog</a>
            <div class="collapse navbar-collapse">

                <ul class="nav navbar-nav navbar-right" id="navigation">
                    {% for href, id, caption in navigation_bar %}
                        <li {% if id == active_page %} class="active"{% endif %}>
                            <a href="{{ href|e }}">{{ caption|e }}</a>
                        </li>
                    {% endfor %}
                </ul>

            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
{% endblock %}

app/templates/login.html
{% extends 'layout.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% set active_page = "/login" %}

{% block content %}
    <div class="container">
        <h1>Please Login:</h1>
        <div class="row">
            <div class="col-md-3">
                {{ wtf.quick_form(form) }}
                <br>
                {% if new %}
                    <div class="alert alert-warning" role="alert">User not found. Please register first.</div>
                {% endif %}
                {% if wrong_pass %}
                    <div class="alert alert-warning" role="alert">Wrong password for user {{ name }}.</div>
                {% endif %}
            </div>
        </div>



        <a href="{{ url_for('main.registration') }}">Registration</a>
    </div>
{% endblock %}

app/templates/posts.html
{% extends 'layout.html' %}
{% set active_page = "/posts" %}

{% block content %}
    <div class="container">
        <h1>Posts page</h1>
    </div>
{% endblock %}

app/templates/registration.html
{% extends 'layout.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% set active_page = "/login" %}

{% block content %}
    <div class="container">
        <h1>New User:</h1>
        <div class="row">
            <div class="col-md-3">
                {{ wtf.quick_form(form) }}
                <br>
                {% if already_exists %}
                    <div class="alert alert-warning" role="alert">User {{ name }} is already exists.</div>
                {% endif %}
            </div>
        </div>
        <br>

    </div>
{% endblock %}

app/templates/welcome.html
{% extends 'layout.html' %}
{% set active_page = "/" %}

{% block content %}
    <div class="container">
        {% if not current_user.is_authenticated %}
            <h1>Welcome!</h1>
        {% else %}
            <h1>Welcome, {{ current_user.name }}!</h1>
        {% endif %}
    </div>
{% endblock %}

templates/login.html
{% extends 'layout.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% set active_page = "/login" %}

{% block content %}
    <div class="container">
        <h1>Please Login:</h1>
        <div class="row">
            <div class="col-md-3">
                {{ wtf.quick_form(form) }}
                <br>
                {% if new %}
                    <div class="alert alert-warning" role="alert">User not found. Please register first.</div>
                {% endif %}
                {% if wrong_pass %}
                    <div class="alert alert-warning" role="alert">Wrong password for user {{ name }}.</div>
                {% endif %}
            </div>
        </div>



        <a href="{{ url_for('registration') }}">Registration</a>
    </div>
{% endblock %}